<a href="https://colab.research.google.com/github/yasaswini0918/my-personal-site-/blob/master/spam_mail_detection_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#description: this code detects the spam mail if its one or zero if not spam

In [ ]:
#importing various libraries
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [ ]:
#loading data
from google.colab import files
uploaded = files.upload()


Saving emails.csv to emails.csv


In [ ]:
#read the CSV file
df = pd.read_csv('emails.csv')
#print first 5 rows of data
df.head(5)

Unnamed: 0  ... label_num
0         605  ...         0
1        2349  ...         0
2        3624  ...         0
3        4685  ...         1
4        2030  ...         0

[5 rows x 4 columns]

In [ ]:
#print the shape(get the number of rows and colums)
df.shape

(49, 4)

In [ ]:
#get the column names
df.columns

Index(['Unnamed: 0', 'label', 'text', 'label_num'], dtype='object')

In [ ]:
#check for duplicates and remove them
df.drop_duplicates(inplace=True)

In [ ]:
#show the new shape(new number of rows and columns)
df.shape

(49, 4)

In [ ]:
#show the number of missing(Na,NaN,NAN)data for each column
df.isnull().sum()

Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

In [ ]:
#download the stopwords package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
def process_text(text):
#1 remove punctuation
#2 remove stopwords
#return a text of clean words
#1
   nonpunc=[char for char in text if char not in string.punctuation]
   nonpunc=''.join(nonpunc)
#2
   clean_words=[word for word in nonpunc.split() if word.lower() not in stopwords.words('english')]
#3
   return clean_words


In [ ]:
#show the tokenization(a list of tokens are also called as lemmas)
df['text'].head().apply(process_text)

0    [Subject, enron, methanol, meter, 988291, foll...
1    [Subject, hpl, nom, january, 9, 2001, see, att...
2    [Subject, neon, retreat, ho, ho, ho, around, w...
3    [Subject, photoshop, windows, office, cheap, m...
4    [Subject, indian, springs, deal, book, teco, p...
Name: text, dtype: object

In [ ]:
#example
message4 = 'hello world hello hello world play'
message5 = 'test test test test one hello'
print(message4)
print()

#convert the text into a matrix of token counts
from sklearn.feature_extraction.text import CountVectorizer
bow4 = CountVectorizer(analyzer=process_text).fit_transform([[message4],[message5]])
print(bow4)
bow4.shape

hello world hello hello world play

  (0, 0)	3
  (0, 4)	2
  (0, 2)	1
  (1, 0)	1
  (1, 3)	4
  (1, 1)	1


(2, 5)

In [ ]:
#convert the text into a matrix of token counts
messages_bow = CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [ ]:
#spit the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(messages_bow, df['label_num'], test_size=0.20, random_state=0)

In [ ]:
#get the shape of messages_bow
messages_bow.shape

(49, 2602)

In [ ]:
#create and train Naives Bayes classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train,Y_train)

In [ ]:
#print the predictions

print(classifier.predict(X_train))
#print actual values

print(Y_train.values)

[1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 1 0]
[1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 1 0]


In [ ]:
#evaluate the model on the training data set
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred= classifier.predict(X_train)
print(classification_report(Y_train, pred))
print()
print('confusion matrix:\n',confusion_matrix(Y_train,pred))
print()
print('accuracy :\n',accuracy_score(Y_train,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00        10

    accuracy                           1.00        39
   macro avg       1.00      1.00      1.00        39
weighted avg       1.00      1.00      1.00        39


confusion matrix:
 [[29  0]
 [ 0 10]]

accuracy :
 1.0


In [ ]:
#print the predictions

print(classifier.predict(X_test))
#print actual values

print(Y_test.values)

[0 0 0 0 0 0 0 1 1 1]
[0 0 0 0 0 0 0 1 1 1]


In [ ]:
#evaluate the model on the training data set
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred= classifier.predict(X_test)
print(classification_report(Y_test, pred))
print()
print('confusion matrix:\n',confusion_matrix(Y_test,pred))
print()
print('accuracy :\n',accuracy_score(Y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         3

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10


confusion matrix:
 [[7 0]
 [0 3]]

accuracy :
 1.0
